spring:
  datasource:
    url: jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/d5qe0fmdf86mde
    username: knascmbrslftqj
    password: d21e234656b059fd486a4a5ab34b1f3974ee0f3631104a16acfed84aab8c3d68
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
